language: python

python:
  - "3.5"
  - "3.6"

env:
  global:
    - FLASK_APP=biblat_manager.app
    - BIBLAT_CONFIG=testing

install:
  - pip install -r requirements.txt

script:
  - flask test --coverage
